[package]
name = "scrypt-rs"
version = "0.3.0"
authors = ["Aitor Pazos <mail@aitorpazos.es>"]

[dependencies]
base64 = "0.13"
bip39 = "1.0.1"
clap = "3.2.22"
hex = "0.4"
regex = "1.5"
rust-crypto = "0.2"
